version: '2'
services:
  headless-client:
    build: dependencies/headless-client
    links:
      - redis
      - postgres
    environment: &environment
      - TOKEN_APP_SEED=ability unit also sauce actual race nothing penalty flush raise shine error
      - TOKEN_APP_USERNAME=SecretBot
      - TOKEN_APP_NAME=Secret Bot
      - TOKEN_APP_AVATAR=attachments/avatar.jpg
      ##
      # Token App Id: 0xfdf1c2c3dfc6b17e517776eb59e4930f759320e9

      # Token App Payment Address: 0xda2f6d81f6ed4dca56b9564f1a1e6fbb7f42c08d
      ##
      - REDIS_URL=redis://h:rlcMWNrxXgqS0xM8aWCYuE0R@redis:6379
      - DATABASE_URL=postgres://token:va5uOdJBqu2dZ1@postgres:5432/token
      - LOG_LEVEL=INFO
      - ENABLE_LOG_TIMESTAMPS=0
    volumes:
      - ./config:/usr/src/headless-client/config
      - ./attachments:/usr/src/headless-client/attachments
  bot:
    build: .
    links:
      - redis
      - postgres
    environment: *environment
    volumes:
      - ./config:/usr/src/bot/config
      - ./src:/usr/src/bot/src
  redis:
    build: dependencies/redis
    ports:
      - 6379
  postgres:
    image: postgres:9.6
    ports:
      - 15432
    environment:
      - POSTGRES_PASSWORD=va5uOdJBqu2dZ1
      - POSTGRES_USER=token
      - POSTGRES_DB=token
